name: S3 Deploy
description: Deploys static website files to S3 and invalidates them in a CloudFront distribution
inputs:
  bucket_name:
    description: Name of the S3 bucket
    required: true
  cloudfront_id:
    description: ID of the CloudFront distribution
    required: false
runs:
  using: docker
  image: Dockerfile
  args: ${{ inputs.bucket_name }} ${{ inputs.cloudfront_id }}