name: S3 Deploy
author: Maurer Labs, LLC
description: Deploys static website files to S3 and invalidates them in a CloudFront distribution
branding:
  color: blue
  icon: database
inputs:
  deploy_dir:
    description: Public directory to deploy to S3
    required: false
  bucket_name:
    description: Name of the S3 bucket
    required: true
  cloudfront_id:
    description: ID of the CloudFront distribution
    required: false
  invalidate_all:
    description: Whether to invalidate all paths, or just the uploaded paths
    required: false
    default: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.deploy_dir }}
    - ${{ inputs.bucket_name }}
    - ${{ inputs.cloudfront_id }}
    - ${{ inputs.invalidate_all }}
