name: S3 Deploy
author: Maurer Labs, LLC
description: Deploys static website files to S3 and invalidates them in a CloudFront distribution
branding:
  color: blue
  icon: database  
inputs:
  deploy_dir:
    description: Public directory to deploy to S3
    required: false
    default: ./
  bucket_name:
    description: Name of the S3 bucket
    required: true
  cloudfront_id:
    description: ID of the CloudFront distribution
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.deploy_dir }}
    - ${{ inputs.bucket_name }}
    - ${{ inputs.cloudfront_id }}