name: S3 Deploy
author: Maurer Labs, LLC
description: Deploys static website files to S3 and invalidates them in a CloudFront distribution
branding:
  color: blue
  icon: database
inputs:
  bucket_name:
    description: Name of the S3 bucket
    required: true
  cloudfront_id:
    description: ID of the CloudFront distribution
    required: false
  base_dir:
    description: Public directory to deploy to S3
    required: false
  invalidate_wildcard:
    description: Whether to invalidate all paths, or just the uploaded paths
    required: false
runs:
  using: docker
  image: Dockerfile
