name: S3 Deploy
author: Maurer Labs, LLC
description: Deploys static website files to S3 and invalidates them in a CloudFront distribution
inputs:
  base_dir:
    description: Filesystem path to deploy
    required: false
  ignore_pattern:
    description: RegExp pattern of paths to ignore
    required: false
  bucket_name:
    description: Name of the S3 bucket
    required: true
  key_prefix:
    description: Subfolder within S3 bucket
    required: false
  object_acl:
    description: ACL to use for uploaded S3 objects
    required: false
  delete_stale_files:
    description: Delete all stale S3 files that are not in local deployment directory
    required: false
  cloudfront_id:
    description: ID of the CloudFront distribution
    required: false
  invalidate_wildcard:
    description: Invalidate all paths using a wildcard vs using a whitelist
    required: false
  invalidate_with_key_prefix:
    description: Prepend key_prefix to all invalidation paths
    required: false
runs:
  using: docker
  image: docker://maurco/action-s3-deploy:latest
