name: Hello World
author: Maurer Labs, LLC
inputs:
  who-to-greet:
    description: Who to greet
    required: true
outputs:
  time:
    description: The time we greeted you
runs:
  using: node12
  main: ../index.js
  args:
    - bin/hello-world
