name: Hello World
author: Maurer Labs, LLC
description: Used for internal testing
inputs:
  who_to_greet:
    description: Who to greet
    required: true
outputs:
  time:
    description: The time we greeted you
runs:
  using: docker
  image: ../Dockerfile
