name: Hello World
author: Maurer Labs, LLC
inputs:
  who_to_greet:
    description: Who to greet
    required: true
outputs:
  time:
    description: The time we greeted you
runs:
  using: node12
  main: index.js
