name: Zola Build
author: Maurer Labs, LLC
description: Builds a site using the Zola static site generator
branding:
  color: black
  icon: package
inputs:
  base_dir:
    description: Base directory to run the build command from
    required: false
  config_file:
    description: Zola config file to use for build
    required: false
  base_url:
    description: Base URL to use for links and the sitemap
    required: false
  output_dir:
    description: Output directory of the compiled site
    required: false
runs:
  using: docker
  image: Dockerfile
