name: Zola Build
author: Maurer Labs, LLC
description: Builds a site using the Zola static site generator
branding:
  color: black
  icon: package
inputs:
  base_dir:
    description: Base directory to run the build command from
    required: false
  output_dir:
    description: Output directory of the compiled site
    required: false
    default: public
  config_file:
    description: Zola config file to use for build
    required: false
    default: config.toml
  prebuild:
    description: Command to run before the Zola site is built
    required: false
  postbuild:
    description: Command to run after the Zola site is built
    required: false
runs:
  using: docker
  image: Dockerfile
